### ISSUE TITLE
Plugin Install Failing

### ISSUE THREAD

**Issue by askovi** [hoobs-org/gui#4]
When you click install on a plugin and create a new bridge the plugin does not install. Instead it redirects to the /config/hub page
This is very confusing because the user clicks install on the plugin page and the modal shows it will install the plugin after the bridge is created

**Comment by mkellsy** [comment]
Fixed

**Comment by askovi** [comment]
This still doesn't work. Same issue, bridge creates but the plugin does not get installed.

**Comment by askovi** [comment]
Seems to only happen on first bridge creation, it worked while creating a secondary bridge when installing a different plugin. 

Didn't work with myq on first myq bridge created
Worked with tplink on 2nd bridge created tplink bridge

**Comment by askovi** [comment]
Nevermind, it didn't actually install. This is weird. It brought me to the configuration page of the tplink plugin but i didn't click save and when i went back into the tplink smarthome bridge it says no plugins installed. Logs also don't show it

`No plugins installed.
3/9/2021, 10:34:58 PM
Tplink Smarthome Bridge
Preparing Advertiser for 'Tplink Smarthome Bridge 863C' using bonjour-hap backend!
3/9/2021, 10:34:58 PM
Tplink Smarthome Bridge
Starting to advertise 'Tplink Smarthome Bridge 863C' using bonjour-hap backend!
3/9/2021, 10:34:58 PM
Tplink Smarthome Bridge
Bridge is running on port 52826.
3/9/2021, 10:35:16 PM
Tplink Smarthome Bridge
WARNING
No plugins installed.
3/9/2021, 10:35:16 PM
Tplink Smarthome Bridge
Loading 1 platforms...
3/9/2021, 10:35:17 PM
Tplink Smarthome Bridge
Preparing Advertiser for 'Tplink Smarthome Bridge 863C' using bonjour-hap backend!
3/9/2021, 10:35:17 PM
Tplink Smarthome Bridge
Starting to advertise 'Tplink Smarthome Bridge 863C' using bonjour-hap backend!
3/9/2021, 10:35:17 PM
Tplink Smarthome Bridge
Bridge is running on port 52826.`

**Comment by askovi** [comment]
Interface crashed when trying to install the tplink plugin again on the bridge. Logs seem fine

`3/9/2021, 8:34:58 PM Tplink Smarthome Bridge  WARNING  No plugins installed.
3/9/2021, 8:34:58 PM Tplink Smarthome Bridge Preparing Advertiser for 'Tplink Sm                          arthome Bridge 863C' using bonjour-hap backend!
3/9/2021, 8:34:58 PM Tplink Smarthome Bridge Starting to advertise 'Tplink Smart                          home Bridge 863C' using bonjour-hap backend!
3/9/2021, 8:34:58 PM Tplink Smarthome Bridge Bridge is running on port 52826.
3/9/2021, 8:35:16 PM Tplink Smarthome Bridge  WARNING  No plugins installed.
3/9/2021, 8:35:16 PM Tplink Smarthome Bridge Loading 1 platforms...
3/9/2021, 8:35:17 PM Tplink Smarthome Bridge Preparing Advertiser for 'Tplink Sm                          arthome Bridge 863C' using bonjour-hap backend!
3/9/2021, 8:35:17 PM Tplink Smarthome Bridge Starting to advertise 'Tplink Smart                          home Bridge 863C' using bonjour-hap backend!
3/9/2021, 8:35:17 PM Tplink Smarthome Bridge Bridge is running on port 52826.
3/9/2021, 8:40:04 PM Tplink Smarthome Bridge Loaded plugin 'homebridge-tplink-sm                          arthome'
3/9/2021, 8:40:04 PM Tplink Smarthome Bridge Registering platform 'homebridge-tp                          link-smarthome.TplinkSmarthome'
3/9/2021, 8:40:04 PM Tplink Smarthome Bridge Loading 1 platforms...
3/9/2021, 8:40:04 PM Tplink Smarthome Bridge TplinkSmarthome homebridge-tplink-s                          marthome v6.3.0, node v14.16.0, homebridge v1.3.2, api v2.7
3/9/2021, 8:40:04 PM Tplink Smarthome Bridge Preparing Advertiser for 'Tplink Sm                          arthome Bridge 863C' using bonjour-hap backend!
3/9/2021, 8:40:04 PM Tplink Smarthome Bridge Starting to advertise 'Tplink Smart                          home Bridge 863C' using bonjour-hap backend!
3/9/2021, 8:40:04 PM Tplink Smarthome Bridge Bridge is running on port 52826.
3/9/2021, 8:40:04 PM Tplink Smarthome Bridge TplinkSmarthome New Device Online:                           [Downstairs Bathroom Fan] plug [8006CC8A6EC54E496329C659D5C664881A9BF27D] 192.16                          8.1.46 9999
3/9/2021, 8:40:04 PM Tplink Smarthome Bridge TplinkSmarthome Adding: [Downstairs                           Bathroom Fan] plug [8006CC8A6EC54E496329C659D5C664881A9BF27D]
3/9/2021, 8:40:04 PM Tplink Smarthome Bridge TplinkSmarthome New Device Online:                           [Upstairs Bathroom Vanity] plug [8006B95BE0EEEC08A0F8A01A6B4E250E1D41E388] 192.1                          68.1.220 9999
3/9/2021, 8:40:04 PM Tplink Smarthome Bridge TplinkSmarthome Adding: [Upstairs B                          athroom Vanity] plug [8006B95BE0EEEC08A0F8A01A6B4E250E1D41E388]
3/9/2021, 8:40:04 PM Tplink Smarthome Bridge TplinkSmarthome New Device Online:                           [Upstairs Bathroom Fan] plug [8006AC6CBFED984AA34FD89963DFD3621D74B037] 192.168.                          1.160 9999
3/9/2021, 8:40:04 PM Tplink Smarthome Bridge TplinkSmarthome Adding: [Upstairs B                          athroom Fan] plug [8006AC6CBFED984AA34FD89963DFD3621D74B037]
3/9/2021, 8:40:05 PM Tplink Smarthome Bridge TplinkSmarthome New Device Online:                           [Outdoor Left] plug [8006BB67201B22CB549C058F049E93701D53A52A00] 192.168.1.171 9                          999
3/9/2021, 8:40:05 PM Tplink Smarthome Bridge TplinkSmarthome Adding: [Outdoor Le                          ft] plug [8006BB67201B22CB549C058F049E93701D53A52A00]
3/9/2021, 8:40:05 PM Tplink Smarthome Bridge  WARNING  [Tplink Smarthome Bridge                           863C@Outdoor Left@Outdoor Left@Amperes] Characteristic not in required or option                          al characteristic section for service Outlet. Adding anyway.
3/9/2021, 8:40:05 PM Tplink Smarthome Bridge  WARNING  [Tplink Smarthome Bridge                           863C@Outdoor Left@Outdoor Left@Total Consumption] Characteristic not in required                           or optional characteristic section for service Outlet. Adding anyway.
3/9/2021, 8:40:05 PM Tplink Smarthome Bridge  WARNING  [Tplink Smarthome Bridge                           863C@Outdoor Left@Outdoor Left@Apparent Power] Characteristic not in required or                           optional characteristic section for service Outlet. Adding anyway.
3/9/2021, 8:40:05 PM Tplink Smarthome Bridge  WARNING  [Tplink Smarthome Bridge                           863C@Outdoor Left@Outdoor Left@Volts] Characteristic not in required or optional                           characteristic section for service Outlet. Adding anyway.
3/9/2021, 8:40:05 PM Tplink Smarthome Bridge  WARNING  [Tplink Smarthome Bridge                           863C@Outdoor Left@Outdoor Left@Consumption] Characteristic not in required or op                          tional characteristic section for service Outlet. Adding anyway.
3/9/2021, 8:40:05 PM Tplink Smarthome Bridge TplinkSmarthome New Device Online:                           [Outdoor Right] plug [8006BB67201B22CB549C058F049E93701D53A52A01] 192.168.1.171                           9999
3/9/2021, 8:40:05 PM Tplink Smarthome Bridge TplinkSmarthome Adding: [Outdoor Ri                          ght] plug [8006BB67201B22CB549C058F049E93701D53A52A01]
3/9/2021, 8:40:05 PM Tplink Smarthome Bridge  WARNING  [Tplink Smarthome Bridge                           863C@Outdoor Right@Outdoor Right@Amperes] Characteristic not in required or opti                          onal characteristic section for service Outlet. Adding anyway.
3/9/2021, 8:40:05 PM Tplink Smarthome Bridge  WARNING  [Tplink Smarthome Bridge                           863C@Outdoor Right@Outdoor Right@Total Consumption] Characteristic not in requir                          ed or optional characteristic section for service Outlet. Adding anyway.
3/9/2021, 8:40:05 PM Tplink Smarthome Bridge  WARNING  [Tplink Smarthome Bridge                           863C@Outdoor Right@Outdoor Right@Apparent Power] Characteristic not in required                           or optional characteristic section for service Outlet. Adding anyway.
3/9/2021, 8:40:05 PM Tplink Smarthome Bridge  WARNING  [Tplink Smarthome Bridge                           863C@Outdoor Right@Outdoor Right@Volts] Characteristic not in required or option                          al characteristic section for service Outlet. Adding anyway.
3/9/2021, 8:40:05 PM Tplink Smarthome Bridge  WARNING  [Tplink Smarthome Bridge                           863C@Outdoor Right@Outdoor Right@Consumption] Characteristic not in required or                           optional characteristic section for service Outlet. Adding anyway.
`

**Comment by askovi** [comment]
I reflashed and tried again. Same issue, slightly different behavior.
Tried with tplink first bridge, it looks like it installed the plugin because it took me to the config page of the plugin. I clicked on logs saw this :

![image](https://user-images.githubusercontent.com/3981552/110574439-191f7180-812b-11eb-9964-3f4425824a76.png)

Then went back to the plugins page clicked the the tplink bridge and it initially showed me the plugin is installed then i clicked back to logs and back to the plugins page and now it says no plugins installed for the tplink bridge.

**Comment by askovi** [comment]
Now i installed the tplink plugin again on the same bridge and everything crashed again

**Comment by askovi** [comment]
![image](https://user-images.githubusercontent.com/3981552/110574687-9e0a8b00-812b-11eb-9177-cc45dd240f04.png)

**Comment by mkellsy** [comment]
I think this is a clash between the link libs and the install. Please quit reporting until the next version.

**Comment by mkellsy** [comment]
I tested this with hoobsd 4.0.15, and I am unable to reproduce now.

I am marking this fixed in 4.0.15
